// <auto-generated />
using System;
using Library.Persistance;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Library.Persistance.Migrations
{
    [DbContext(typeof(LibraryDBContext))]
    partial class LibraryDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.20");

            modelBuilder.Entity("Library.Domain.Author", b =>
                {
                    b.Property<Guid>("author_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("author_id");

                    b.Property<DateOnly?>("author_birthday")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("author_birthday");

                    b.Property<string>("author_country")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("author_country");

                    b.Property<string>("author_firstname")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("author_firstname");

                    b.Property<string>("author_lastname")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("author_lastname");

                    b.HasKey("author_id");

                    b.ToTable("authors");
                });

            modelBuilder.Entity("Library.Domain.Book", b =>
                {
                    b.Property<Guid>("book_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("book_id");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("book_ISBN");

                    b.Property<Guid>("author_id")
                        .HasColumnType("TEXT");

                    b.Property<string>("book_description")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("book_descr");

                    b.Property<string>("book_genre")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("book_genre");

                    b.Property<DateTime>("book_issue_date")
                        .HasColumnType("TEXT")
                        .HasColumnName("book_issue_date");

                    b.Property<DateTime>("book_issue_expiration_date")
                        .HasColumnType("TEXT")
                        .HasColumnName("book_issue_expiration_date");

                    b.Property<string>("book_name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("book_name");

                    b.HasKey("book_id");

                    b.HasIndex("author_id");

                    b.ToTable("books");
                });

            modelBuilder.Entity("Library.Domain.Book", b =>
                {
                    b.HasOne("Library.Domain.Author", "author")
                        .WithMany("books")
                        .HasForeignKey("author_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("author");
                });

            modelBuilder.Entity("Library.Domain.Author", b =>
                {
                    b.Navigation("books");
                });
#pragma warning restore 612, 618
        }
    }
}
